[package]
name = "plugin1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loader = { path = "../loader" }
log = "0.4.21"

[lib]
name = "plugin1"
path = "plugin1.rs"
crate-type = ["cdylib", "rlib"]