[package]
name = "rust-as-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loader = { path = "../loader" }
ferris-says = "0.3.1"
log = "0.4.21"
error-chain = "0.12.4"
anyhow = "1.0.82"